---
- hosts: cat23.dh.kevinmylab.com
  become: true
  become_method: sudo
  become_user: root
  vars:
    # Use "targeted" SELinux policy type
    selinux_policy: targeted
    # Set "enforcing" mode
    selinux_state: enforcing
    # SELinux file type
    selinux_fcontexts:
      - { target: '/taco(/.*)?', setype: 'httpd_sys_content_t', ftype: 'd' }
    # Restore SELinux file contexts in '/taco'
    selinux_restore_dirs:
      - /taco

  # Prepare the prerequisites required for this playbook
  tasks:
    - name: Creates directory
      file:
        path: /taco
        state: directory
        mode: "0755"
        
    - name: execute the role and catch errors
      block:
        - name: Include selinux role
          include_role:
            name: kage
      rescue:
        # Fail if failed for a different reason than selinux_reboot_required.
        - name: handle errors
          fail:
            msg: "role failed"
          when: not selinux_reboot_required

        - name: restart managed host
          reboot:

        - name: wait for managed host to come back
          wait_for_connection:
            delay: 10
            timeout: 300

        - name: reapply the role
          include_role:
            name: kage
        
    - name: Creating Index.html in /taco
      lineinfile:
        path: /taco/index.html
        create: true
        line: 'Welcome Kevin to your Webserver'    
        state: present

- name: Importing another playbook #Could be on the top of the playbook as well.Needs to be down at the end for this playbook, however.
  import_playbook: line.yaml

- name: Testing server
  hosts: localhost
  tasks:
   - name: Test Server
     uri:
        url: http://cat23.dh.kevinmylab.com
        return_content: yes
     register: oklm
     ignore_errors: true

   - name: debug web
     debug:
        var: oklm.content
     when: '"Welcome" in oklm.content'
